export const SET_REALM = "SET_REALM";
export const SET_CANDLE = "SET_CANDLE";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const ADD_CANDLE_START = "PURCHASE_BURGER_START";
export const ADD_CANDLE_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const ADD_CANDLE_FAIL = "PURCHASE_BURGER_FAIL";

export const FETCH_CANDLES_START = "FETCH_ORDERS_START";
export const FETCH_CANDLES_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_CANDLES_FAIL = "FETCH_ORDERS_FAIL";