export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const EDIT_CANDLE_START = "EDIT_CANDLE_START";

export const ADD_CANDLE_SUCCESS = "ADD_CANDLE_SUCCESS";
export const REMOVE_CANDLE_SUCCESS = "REMOVE_CANDLE_SUCCESS";

export const EDIT_CANDLE_FAIL = "EDIT_CANDLE_FAIL";

export const FETCH_CANDLES_START = "FETCH_CANDLES_START";
export const FETCH_CANDLES_SUCCESS = "FETCH_CANDLES_SUCCESS";
export const FETCH_CANDLES_FAIL = "FETCH_CANDLES_FAIL";

export const EDIT_REALM_START = "EDIT_REALM_START";

export const ADD_REALM_SUCCESS = "ADD_REALM_SUCCESS";
export const REMOVE_REALM_SUCCESS = "REMOVE_REALM_SUCCESS";

export const EDIT_REALM_FAIL = "EDIT_REALM_FAIL";

export const FETCH_REALMS_START = "FETCH_REALMS_START";
export const FETCH_REALMS_SUCCESS = "FETCH_REALMS_SUCCESS";
export const FETCH_REALMS_FAIL = "FETCH_REALMS_FAIL";